# # https://packaging.python.org/guides/supporting-windows-using-appveyor/
skip_non_tags: true
environment:
  matrix:
    - PYTHON: "C:\\Python27"
install:
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install wheel"
build_script:
  - "%PYTHON%\\python.exe setup.py bdist_wheel"
artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*
deploy:
- provider: GitHub
  auth_token:
    secure: ux+wDa1xjiEw4ZWqCD49D5SMSb7OjNWejQ/yr06+4Dvq410krXA9aybgu+DjQfcL
  repository: stuartleeks/az-cli-extension-show-deployment
  artifact: 'dist\*.whl'
  draft: true