# # https://packaging.python.org/guides/supporting-windows-using-appveyor/
# skip_non_tags: true
environment:
  matrix:
    - PYTHON: "C:\\Python27"
install:
  # We need wheel installed to build wheels
  - "%PYTHON%\\python.exe -m pip install wheel"
build_script:
  - "%PYTHON%\\python.exe setup.py bdist_wheel"
artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*
